---
abstract: 'Make valid NCName tokens which are also UUIDs.'
author:
  - 'Dorian Taylor, C<< <dorian at cpan.org> >>'
  - 'Dorian Taylor <dorian@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-UUID-NCName
no_index:
  directory:
    - inc
    - t
requires:
  MIME::Base32: 0
  MIME::Base64: 0
  perl: 5.8.0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.01
